-- Personal Coin Scanner: initial schema (see coin_app_requirements.md §4.1)

create table albums (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default now()
);

create table personal_coins (
    id bigint generated by default as identity primary key,
    country text not null,
    denomination text not null,
    mint_year int2,
    mint_mark text,
    image_path text not null,          -- Storage object path, not a public URL
    image_quality_score int2,          -- Gemini-estimated clarity 0-100, shown as a hint during duplicate review
    quantity int2 not null default 1,  -- how many specimens owned matching this identity
    personal_notes text,
    album_id bigint references albums(id),  -- nullable: set once physically placed; never set on duplicates beyond the first
    page_number int2,                       -- free-form sequential page index within the album
    pocket_number int2,                     -- free-form sequential pocket index within the page
    created_at timestamptz not null default now()
);

-- Speeds up the duplicate-check query (see §3.5).
create index idx_personal_coins_dedup on personal_coins (country, denomination, mint_year, mint_mark);

alter table albums enable row level security;
alter table personal_coins enable row level security;
-- No auth.uid() policies: single-user app, all access goes through Edge
-- Functions using the service-role key, which bypasses RLS by design.
-- RLS is enabled anyway so the anon/public key grants zero access by default.

insert into storage.buckets (id, name, public)
values ('coin-photos', 'coin-photos', false)
on conflict (id) do nothing;
-- Bucket is private; the client never gets direct storage access. Reads go
-- through signed URLs minted by an Edge Function using the service-role key.
