-- Mint mark resolution (see coin_app_requirements.md §3.7, §4.1)

create table mints (
    id bigint generated by default as identity primary key,
    country text not null,
    mint_mark text not null,
    mint_name text not null,
    created_at timestamptz not null default now(),
    unique (country, mint_mark)
);

alter table personal_coins
    add column mint_id bigint references mints(id);

alter table mints enable row level security;
