-- Conditional mint mark resolution (see coin_app_requirements.md §3.7).
-- Replaces the single (country, mint_mark) -> mint_name mapping with rules
-- that can also key off the coin's mint_year (a range) or the mark's
-- position relative to a digit of the year — covers real cases already in
-- the data: India's star/diamond position marks (Seoul/Taegu vs Hyderabad,
-- London vs Mumbai), the US Denver-vs-Dahlonega "D" year split, and a
-- Mexico City mark correction (M -> OM).

create table mint_mark_rules (
    id bigint generated by default as identity primary key,
    country text not null,
    mint_mark text not null,
    condition_type text not null check (condition_type in ('default', 'year_range', 'position')),
    year_min int2,
    year_max int2,
    position text check (position is null or position in ('first_digit', 'last_digit')),
    mint_id bigint not null references mints(id) on delete cascade,
    created_at timestamptz not null default now(),
    check ((condition_type = 'year_range') = (year_min is not null and year_max is not null)),
    check ((condition_type = 'position') = (position is not null))
);

-- At most one fallback rule per (country, mark) — year_range/position rules
-- for the same mark are allowed to coexist since they're mutually exclusive
-- by condition, not by a DB constraint (small hand-curated dataset).
create unique index mint_mark_rules_default_key on mint_mark_rules (country, mint_mark)
    where condition_type = 'default';

alter table mint_mark_rules enable row level security;

alter table personal_coins add column mint_mark_position text
    check (mint_mark_position is null or mint_mark_position in ('first_digit', 'last_digit'));

-- Backfill: every existing `mints` row becomes a plain 'default' rule,
-- except the four handled specially below.
insert into mint_mark_rules (country, mint_mark, condition_type, mint_id)
select country, mint_mark, 'default', id
from mints
where id not in (9, 13, 14, 24);

-- India ★ position workarounds ("★ Below the last/fist digit of the Year")
-- -> Seoul Mint (id 13) / Taegu Mint (id 14).
insert into mint_mark_rules (country, mint_mark, condition_type, position, mint_id) values
    ('India', '★', 'position', 'last_digit', 13),
    ('India', '★', 'position', 'first_digit', 14);

-- US "D (1838-1861)" workaround -> Dahlonega (id 24).
insert into mint_mark_rules (country, mint_mark, condition_type, year_min, year_max, mint_id) values
    ('United States of America', 'D', 'year_range', 1838, 1861, 24);

-- Mexico City's actual mark is a stacked "OM", not a lone "M" (id 9).
insert into mint_mark_rules (country, mint_mark, condition_type, mint_id) values
    ('India', 'OM', 'default', 9);

-- US "P" (id 18) and pre-1980 "No Mark" (id 19) both mean Philadelphia —
-- the mark was only added starting 1980, same physical mint either way.
-- Merge into one identity (keep 18) before (country, mint_name) must be
-- unique below; both rules end up pointing at the same mint.
update mint_mark_rules set mint_id = 18 where mint_id = 19;
delete from mints where id = 19;

-- mints becomes a pure identity table; the mark now lives on the rules.
-- Done here (before the new London row below) since mint_mark is still
-- NOT NULL until this drop, and the new row has no mark of its own.
-- CASCADE drops the old (country, mint_mark) unique constraint along with
-- the column, whatever its auto-generated name turns out to be.
alter table mints drop column mint_mark cascade;
alter table mints add constraint mints_country_mint_name_key unique (country, mint_name);

-- New: India ♦ below the first digit of the year -> Royal Mint, London,
-- previously missing from the table (naming matches the existing
-- "Heaton Mint (UK)" / "Tower Mint (UK)" style — rename from the Mints
-- tab if a different wording is preferred).
insert into mints (country, mint_name)
values ('India', 'Royal Mint, London (UK)');

insert into mint_mark_rules (country, mint_mark, condition_type, position, mint_id)
select 'India', '♦', 'position', 'first_digit', id from mints
where country = 'India' and mint_name = 'Royal Mint, London (UK)';
